image: python:2-stretch

variables:
  DEBIAN_FRONTEND: noninteractive
  LANG: en_US.UTF-8
  LANGUAGE: en_US:en
  LC_ALL: en_US.UTF-8
  ANSIBLE_FORCE_COLOR: 'true'

before_script:
  - apt-get update
  - apt-get install -y locales
  - echo "${LANG} UTF-8" > /etc/locale.gen
  - locale-gen ${LANG}
  - apt-get install -y python3-pip
  - pip install ansible
  - pip install flake8
  - pip install ansible-lint

ansible-test:
  stage: test
  script:
    - ansible --version
    - flake8 --version
    - ansible-lint --version
    - ansible-galaxy install -r requirements.yml
    # remove secrets
    - find . -name '*.vault.*' -delete
    - export EXT_ROLES_DIRS=$(find . -mindepth 2 -name ".galaxy_install_info" -printf "%h " | xargs -n 1 dirname)
    - flake8 --exclude=$(echo ${EXT_ROLES_DIRS} | tr ' ' ',') --ignore=E126,E131,E501,E303 .
    - ansible-lint -p --nocolor $(echo ${EXT_ROLES_DIRS} | sed -r 's/\./--exclude=\./g') playbooks/*.yml
    - find playbooks/ -maxdepth 1 -name '*.yml' | xargs -n 1 ansible-playbook --syntax-check

