---
all:
  vars:
    ansible_user: root

  hosts:
    # not yet managed using Ansible
    #pulp-repo.osci.io:
    www.pulpproject.org:
      ansible_host: 8.43.85.236   # until the DNS is updated
    pulp-web-builder.int.osci.io:
      ansible_python_interpreter: /usr/bin/python3

  children:
    cage_zone:
      hosts:
        #pulp-repo.osci.io:
        www.pulpproject.org:
      children:
        cage_internal_zone:
          hosts:
            pulp-web-builder.int.osci.io:

    web_builders:
      hosts:
        pulp-web-builder.int.osci.io:

