---
- hosts: all
  roles:
  - base
  - entropy
  - guest_virt_tools
  - selinux
  - openssh
  - admin_ssh_keys
  - unattended_updates
  - role: chrony
    servers_preferred: "{{ ntp_servers | default([]) }}"
  tags: base

- hosts: www.pulpproject.org
  tasks:
    - name: create web builder's user
      user:
        name: "{{ websync_user }}"
        comment: "Web Builder User"
    - name: "Create vhost for {{ inventory_hostname }}"
      include_role:
        name: httpd
        tasks_from: vhost
      vars:
        # use vhost without 'www.' as main URL
        website_domain: pulpproject.org
        server_aliases:
          - www.pulpproject.org
        document_root: "{{ websync_path }}"
        document_root_group: "{{ websync_user }}"
        use_tls: True
        use_letsencrypt: True
        force_tls: True
    - name: Install redirection to canonical vhost
      copy:
        src: "{{ inventory_dir }}/data/web/www_canonical_redirection.conf"
        dest: "{{ _vhost_confdir }}/"
        owner: root
        group: root
        mode: 0644
      notify: verify config and restart httpd

- hosts: web_builders
  vars:
    website_username: web_builder
  roles:
  - role: builder
    name: "{{ website_name }}"
    builder: "{{ website_builder | default('middleman') }}"
    builder_username: "{{ website_username }}"
    git_url: "{{ website_repo_url }}"
    git_version: "{{ website_repo_version }}"
    auto_deploy_hour: "*/6"
    # until it is stable enough to spam the team :-)
    cron_error_email: "{{ pulp_builder_error_email }}"
  - role: msmtp
    smart_host: "{{ mail_forwarder }}"
    disable_freeipa: true

- hosts: www.pulpproject.org
  vars:
    doc_vhost: docs.pulpproject.org
    doc_user: doc_builder
  tasks:
    - name: doc builder's user
      user:
        name: "{{ doc_user }}"
        comment: "Doc Builder User"
    - name: "Create vhost for {{ doc_vhost }}"
      include_role:
        name: httpd
        tasks_from: vhost
      vars:
        website_domain: "{{ doc_vhost }}"
        document_root: "/var/www/{{ doc_vhost }}"
        document_root_group: "{{ doc_user }}"
        # uncomment during migration
        #use_tls: True
        #use_letsencrypt: True
        #force_tls: True
    # rsync is already installed for the web builder sync
    - name: Install doc builder's SSH keys
      authorized_key:
          key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDNfEAXdhT7mIf4d+XOWvE4hw5uduVyqc1N3ttqHV/5SM37XWHvln9D0IzMtDllXrmvlFuUA8sUCnc3zw3s+zIFh0ln+nhEQAo3StvchmlzmYJD1VyS1e8Pfd9xnD8DOBQNdy3aq4ZVrLtCAYndfX1Y5sfqlgN35OQ+7frjKaJXQWVHuLDGTxWR/y82EOT5JyXPyZd6B9VsQRPmB5oK1eSqMNQikuXJITDRxK6olfIdLzze85gV0aRJYo6GD5Aj68SciIsR95y//afwOQZr8m7OjygTsxLTlzsoRVR2N4uTyOe2i2szqy9kxUnvTiTVDULWicQZLBmv7S1pjaytKJnj pulp-doc-builder"
          key_options: "command=\"rsync --server -vlogtrze.isf --delete-after --omit-dir-times . /var/www/{{ doc_vhost }}\",no-port-forwarding,no-agent-forwarding,no-X11-forwarding,no-pty"
          user: "{{ doc_user }}"

