---
- hosts: all
  roles:
  - base
  - entropy
  - guest_virt_tools
  - selinux
  - openssh
  - admin_ssh_keys
  - unattended_updates
  - role: chrony
    servers_preferred: "{{ ntp_servers | default([]) }}"
  tags: base

